### ISSUE TITLE
crash when i press the arrow keys

### ISSUE THREAD

**Issue by MAJigsaw77** [BeastlyGhost/Forever-Engine-Legacy#15]
states/PlayState.hx (line 629)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/BeastlyGhost/Forever-Engine-Legacy
on the "custom-build" branch

>Crash Handler written by: sqirra-rng

**Comment by BeastlyGhost** [comment]
fixed on latest, it was something with notetypes
